// Dimensiones de las imágenes de public/images (optimizadas a WebP desde el portfolio en PDF).
export type Img = { src: string; width: number; height: number };

export const img = {
  logoWicWhite: { src: "/images/logoWicWhite.webp", width: 569, height: 236 },
  logoWicYellow: { src: "/images/logoWicYellow.webp", width: 569, height: 236 },
  logoAlmaq: { src: "/images/logoAlmaq.webp", width: 640, height: 583 },
  logoSoles: { src: "/images/logoSoles.webp", width: 800, height: 251 },
  logoNpp: { src: "/images/logoNpp.webp", width: 900, height: 298 },
  logoJucunajoMark: { src: "/images/logoJucunajoMark.webp", width: 229, height: 179 },
  heroStairs: { src: "/images/heroStairs.webp", width: 2000, height: 1334 },
  teamAriana: { src: "/images/teamAriana.webp", width: 640, height: 640 },
  teamJuanPablo: { src: "/images/teamJuanPablo.webp", width: 640, height: 640 },
  teamFrank: { src: "/images/teamFrank.webp", width: 640, height: 640 },
  logofolioBg: { src: "/images/logofolioBg.webp", width: 1920, height: 1280 },
  panaCard: { src: "/images/panaCard.webp", width: 1400, height: 933 },
  panaCap: { src: "/images/panaCap.webp", width: 436, height: 476 },
  panaLogo: { src: "/images/panaLogo.webp", width: 345, height: 953 },
  almaqField: { src: "/images/almaqField.webp", width: 1000, height: 1337 },
  almaqHelmet: { src: "/images/almaqHelmet.webp", width: 605, height: 347 },
  almaqWorker: { src: "/images/almaqWorker.webp", width: 800, height: 1200 },
  almaqCup: { src: "/images/almaqCup.webp", width: 900, height: 900 },
  mileydyWindow: { src: "/images/mileydyWindow.webp", width: 539, height: 368 },
  mileydyStickers: { src: "/images/mileydyStickers.webp", width: 368, height: 368 },
  mileydyGift: { src: "/images/mileydyGift.webp", width: 575, height: 384 },
  mileydyStore: { src: "/images/mileydyStore.webp", width: 461, height: 392 },
  jucunajoCard: { src: "/images/jucunajoCard.webp", width: 1200, height: 846 },
  jucunajoField: { src: "/images/jucunajoField.webp", width: 600, height: 397 },
  jucunajoTruck: { src: "/images/jucunajoTruck.webp", width: 487, height: 464 },
  wjMug: { src: "/images/wjMug.webp", width: 358, height: 320 },
  wjPaper: { src: "/images/wjPaper.webp", width: 499, height: 455 },
  wjTee: { src: "/images/wjTee.webp", width: 1152, height: 878 },
  clientsBg: { src: "/images/clientsBg.webp", width: 1920, height: 1280 },
  solesTeam: { src: "/images/solesTeam.webp", width: 1400, height: 788 },
  solesFeed: { src: "/images/solesFeed.webp", width: 975, height: 517 },
  solesStand: { src: "/images/solesStand.webp", width: 634, height: 1126 },
  solesAd: { src: "/images/solesAd.webp", width: 239, height: 438 },
  solesMetrics1: { src: "/images/solesMetrics1.webp", width: 897, height: 391 },
  solesMetrics2: { src: "/images/solesMetrics2.webp", width: 885, height: 400 },
  solesCalendar: { src: "/images/solesCalendar.webp", width: 576, height: 363 },
  nppKit: { src: "/images/nppKit.webp", width: 1080, height: 721 },
  nppFeed: { src: "/images/nppFeed.webp", width: 971, height: 519 },
  almaqEvent: { src: "/images/almaqEvent.webp", width: 1000, height: 1333 },
  almaqFeed: { src: "/images/almaqFeed.webp", width: 971, height: 517 },
  webBg: { src: "/images/webBg.webp", width: 1920, height: 1023 },
  videoBg: { src: "/images/videoBg.webp", width: 1920, height: 1280 },
  printBg: { src: "/images/printBg.webp", width: 1920, height: 1280 },
  printCalendar: { src: "/images/printCalendar.webp", width: 724, height: 534 },
  printStock: { src: "/images/printStock.webp", width: 386, height: 285 },
  book1: { src: "/images/book1.webp", width: 791, height: 527 },
  book2: { src: "/images/book2.webp", width: 699, height: 394 },
  book3: { src: "/images/book3.webp", width: 682, height: 384 },
  book4: { src: "/images/book4.webp", width: 795, height: 530 },
  cresfoodPack: { src: "/images/cresfoodPack.webp", width: 584, height: 594 },
  cresfoodLabel: { src: "/images/cresfoodLabel.webp", width: 306, height: 766 },
} as const satisfies Record<string, Img>;
